//--------------------------------------------------------------------------------
// Auto-generated by LiteX (a32096e80) on 2024-12-05 08:59:35
//--------------------------------------------------------------------------------
#ifndef __GENERATED_SOC_H
#define __GENERATED_SOC_H
#define CONFIG_PLATFORM_NAME "litex_m2sdr_platform"
#define CONFIG_CLOCK_FREQUENCY 125000000
#define CONFIG_CPU_TYPE_NONE
#define CONFIG_CPU_VARIANT_STANDARD
#define CONFIG_CPU_FAMILY
#define CONFIG_CPU_NAME
#define CONFIG_CPU_HUMAN_NAME "Unknown"
#define CONFIG_IDENTIFIER "LiteX-M2SDR SoC / m2 variant / built on 2024-12-05 08:59:34"
#define CONFIG_FLASH_IMAGE_SIZE 8388608
#define DMA_CHANNELS 1
#define DMA_ADDR_WIDTH 64
#define PCIE_DMA0_READER_INTERRUPT 0
#define PCIE_DMA0_WRITER_INTERRUPT 1
#define CONFIG_CSR_DATA_WIDTH 32
#define CONFIG_CSR_ALIGNMENT 32
#define CONFIG_BUS_STANDARD "wishbone"
#define CONFIG_BUS_DATA_WIDTH 32
#define CONFIG_BUS_ADDRESS_WIDTH 32
#define CONFIG_BUS_BURSTING 0

#endif
