//--------------------------------------------------------------------------------
// Auto-generated by scripts/gen_kernel_headers.py: the CSR map shared by every supported
// build configuration (see litex_m2sdr/build_configs.py). Do not edit -- re-run the script.
//--------------------------------------------------------------------------------
#ifndef __GENERATED_MEM_H
#define __GENERATED_MEM_H

#ifndef CSR_BASE
#define CSR_BASE 0x00000000L
#define CSR_SIZE 0x00020000
#endif

#ifndef SATA_HOST_BUFFER_BASE
#define SATA_HOST_BUFFER_BASE 0x00020000L
#define SATA_HOST_BUFFER_SIZE 0x00020000
#endif

#ifndef MEM_REGIONS
#define MEM_REGIONS "CSR               0x00000000 0x20000 \nSATA_HOST_BUFFER  0x00020000 0x20000 "
#endif

#ifndef MEM_REGIONS_DETAILS
#define MEM_REGIONS_DETAILS "Region           Origin     End        Size \nCSR              0x00000000 0x0001ffff 0x20000 \nSATA_HOST_BUFFER 0x00020000 0x0003ffff 0x20000 "
#endif
#endif
