//--------------------------------------------------------------------------------
// Auto-generated by LiteX (1693b9eba) on 2026-04-30 10:20:20
//--------------------------------------------------------------------------------
#ifndef __GENERATED_SOC_H
#define __GENERATED_SOC_H
#define CONFIG_PLATFORM_NAME "litex_m2sdr_platform"
#define CONFIG_CLOCK_FREQUENCY 125000000
#define CONFIG_CPU_HAS_INTERRUPT
#define CONFIG_CPU_RESET_ADDR 0
#define CONFIG_CPU_HAS_DCACHE
#define CONFIG_CPU_HAS_ICACHE
#define CONFIG_CPU_TYPE_VEXRISCV
#define CONFIG_CPU_VARIANT_STANDARD
#define CONFIG_CPU_FAMILY "riscv"
#define CONFIG_CPU_NAME "vexriscv"
#define CONFIG_CPU_HUMAN_NAME "VexRiscv"
#define CONFIG_CPU_NOP "nop"
#define CONFIG_IDENTIFIER "LiteX-M2SDR SoC / baseboard variant / built on 2026-04-30 10:16:47"
#define CONFIG_FLASH_IMAGE_SIZE 8388608
#define CONFIG_CSR_DATA_WIDTH 32
#define CONFIG_CSR_ALIGNMENT 32
#define CONFIG_CSR_ORDERING_BIG
#define CONFIG_BUS_STANDARD "wishbone"
#define CONFIG_BUS_DATA_WIDTH 32
#define CONFIG_BUS_ADDRESS_WIDTH 32
#define CONFIG_BUS_BURSTING 0
#define CONFIG_CPU_INTERRUPTS 2
#define TIMER0_INTERRUPT 1
#define UART_INTERRUPT 0

#endif
