//--------------------------------------------------------------------------------
// Auto-generated by LiteX (9d46dff95) on 2026-07-02 10:14:35
//--------------------------------------------------------------------------------
#ifndef __GENERATED_SOC_H
#define __GENERATED_SOC_H
#define CONFIG_PLATFORM_NAME "litex_m2sdr_platform"
#define CONFIG_CLOCK_FREQUENCY 125000000
#define CONFIG_CPU_TYPE_NONE
#define CONFIG_CPU_VARIANT_STANDARD
#define CONFIG_CPU_FAMILY
#define CONFIG_CPU_NAME "None"
#define CONFIG_CPU_HUMAN_NAME "Unknown"
#define CONFIG_IDENTIFIER "LiteX-M2SDR SoC / m2 variant / built on 2026-07-02 10:14:35"
#define CONFIG_FLASH_IMAGE_SIZE 8388608
#define DMA_CHANNELS 1
#define DMA_ADDR_WIDTH 64
#define PCIE_DMA0_READER_INTERRUPT 0
#define PCIE_DMA0_WRITER_INTERRUPT 1
#define CONFIG_CSR_DATA_WIDTH 32
#define CONFIG_CSR_ALIGNMENT 32
#define CONFIG_CSR_ORDERING_BIG
#define CONFIG_BUS_STANDARD "wishbone"
#define CONFIG_BUS_DATA_WIDTH 32
#define CONFIG_BUS_ADDRESS_WIDTH 32
#define CONFIG_BUS_BURSTING 0
#define XADC_HWMON_TEMP_SCALE 503975
#define XADC_HWMON_TEMP_DIVISOR 4096
#define XADC_HWMON_TEMP_OFFSET 273150
#define XADC_HWMON_VOLTAGE_SCALE 3000
#define XADC_HWMON_VOLTAGE_DIVISOR 4096

#endif
